version: "3.9"

services:

  mongo:
    image: bitnami/mongodb
    restart: unless-stopped
    env_file: .env
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - mongo-data:/bitnami/mongodb
  eventstore.db:
    image: docker.eventstore.com/eventstore-preview/eventstoredb-ee:24.10.0-preview1-x64-8.0-bookworm-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_NODE_PORT=${EVENTSTORE_NODE_PORT:-2113}
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "${EVENTSTORE_NODE_PORT:-2113}:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  

volumes:
  mongo-data:
  eventstore-volume-logs:
  eventstore-volume-data: